### ISSUE TITLE
Node categories

### ISSUE THREAD

**Issue by nokome** [stencila/schema#102]
We have the notion of a `category` for each schema type:

https://github.com/stencila/schema/blob/b4c8aa4a7f005621b7de5f14fcffda58bde75f01/src/schema.d.ts#L32-L35

Previously it was populated by the name of the suvdirectory that the schema file was in e.g. `text`, `code`. Now that we have moved to a flat file layout it is not being used.

I think that it would still be useful to have categories of nodes in the documentation and suggest these four:

  - `prose`
  - `data`
  - `code`
  - `metadata`

These categories emphasise the difference between this schema and other document schemas -  which usually only focus on one or two of these categories eg. Jupyter (prose + code), Word, Markdown etc (prose), JATS (prose + metadata), CSV (data).

This would require us to go through and manually add a category to each schema (as we do for `role` etc. Should we stick with the property name `category` or change to `categories` or `keywords` or `tags` - my vote is `categories` to allow schema types to be assigned to more than one category.

**Comment by beneboy** [comment]
Going ahead with just a single entry for each `category`

**Comment by nokome** [comment]
Closed via #123
