### ISSUE TITLE
Add index page for generated website

### ISSUE THREAD

**Issue by alex-ketch** [stencila/schema#118]
Currently clicking on the link to the docs greets the user with a 404 error because the generated website is missing an `index.html` file.

Going directly to the schema however works: https://stencila.github.io/schema/Brand.html

We should make the website more welcoming by generated an index file.

**Comment by nokome** [comment]
Yeah agreed this is sorely needed and this is what #89 is meant to provide. I'm probably going to work on that next week.

**Comment by beneboy** [comment]
Added branch https://github.com/stencila/schema/tree/118-generate-docs-index

Currently just lists dir and creates List of Links to all existing .md (.html) docs in `DocList.json`

**Comment by 100ideas** [comment]
I couldn't get the docs to compile at all. If you check travis/netlify, you can see the doc build step crashes.

So I [forked the repo](https://github.com/100ideas/schema) and made some local changes to recover doc html generation. I am not suggesting this fork be merged, I just wanted to learn more about the schema package. But if anyone is looking for html docs, cloning my fork and running `npm run docs:serve&; npm run regen` might generate them.

Also, here is a zip file of the `dist/` directory of the html docs: [2019-09-23_stencila-schema-jank-htmldocs.zip](https://github.com/100ideas/schema/blob/master/2019-09-23_stencila-schema-jank-htmldocs.zip)

implemented two experiments as well:

1. use `public/<type>.schema.md` as source for a Type's html page if there is no hand-written `schema/<type>.md` file. A notification is included in the html header area if this happens.

2. try to transclude correct examples from `examples/<typeTitle>/*.<typeTitle.yaml` at the bottom of each generated html file.

**Comment by nokome** [comment]
@100ideas Thanks for all your work and patience on this  :pray: . We got busy with other things and have not had time to work on these docs for some time. But I was just mentioning to @alex-ketch and @beneboy yesterday that I was hoping to get back to them this week.

I've had a quick look through your fork and think there are some useful changes in there that I am keen to incorporate them. It might be easiest to start a new PR here, make you a collaborator on it, and work with you to pull over some of those changes to get the docs build again! What do you think?

**Comment by 100ideas** [comment]
@nokome Alright, my pleasure.

Also, I adjusted the index.html generated by `docs:serve: browser-sync...` and saved it to the `public/`, then uploaded to my repos `gh-pages` branch. So here are the docs: https://100ideas.github.io/schema/

**Comment by 100ideas** [comment]
@nokome no rush :) 

by the way, when you were designing the schema generation and management architecture, did you consider using an js libs that provide algebraic data types? 

I'm working on more of a schemaless notebook tool that nonetheless tries to do some helpful autocompletions and suggestions based on inspecting property names, column names, and data types and although I know very little about ADTs, from what I've read it feels like it could be a more efficient and powerful approach. What do you all think?

**Comment by alex-ketch** [comment]
Closed by https://github.com/stencila/schema/pull/150/commits/b6c1775005253fbc0ce26aabd6c95ad28cd41a62
