### ISSUE TITLE
Allow support for having BlockContent inside TableCell

### ISSUE THREAD

**Issue by alex-ketch** [stencila/schema#136]
Another issue of wild HTML encounters! 🎉 

Currently the [TableCell content](https://github.com/stencila/schema/blob/master/schema/TableCell.schema.yaml#L46-51) only supports `InlineContent`.
This causes in issue in Encoda when trying to encode some valid HTML to Schema.

```html
<td>
  <p> my semantically encoded text</p>
  <ul>
    <li>item 1</li>
    <li>item 2</li>
  </ul>
</td>
```

Of note, many of the other formats allow for similar structure:
- [HTML](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/a#Properties): "Permitted content | Transparent, containing either flow content (excluding interactive content) or phrasing content."
- [JATS](https://jats.nlm.nih.gov/articleauthoring/tag-library/1.2/element/td.html): `<td>` is similar to HTML and allows for BlockContent
- [Pandoc](https://github.com/jgm/pandoc-types/blob/1.17.5.4/Text/Pandoc/Definition.hs#L202): Pandoc allows for BlockContent as children
- [OpenDocument](http://docs.oasis-open.org/office/v1.2/os/OpenDocument-v1.2-os-part1.html#__RefHeading__1415590_253892949): "able cell can contain paragraphs and other text content as well as sub tables."
- [MDAST](https://github.com/syntax-tree/mdast#tablecell): Allows for `PhrasingContent`

## Proposal
- Change `TableCell` content to support `BlockContent`
    - This will mean that we might need to support special transformations when encoding to Markdown with things like nested tables, and lists.

> _**Note**_
> _I'm silly and the original issue was for images inside Links. But that's already supported, I had encountered a different issue which prompted me to think otherwise 🤦‍♂_

**Comment by nokome** [comment]
+1 seems appropriate

**Comment by nokome** [comment]
I think we should go ahead and make this change. Just to note that MDAST's [`StaticPhrasingContent`](https://github.com/syntax-tree/mdast#staticphrasingcontent) is very close to out`InlineContent`, but yes, all those other schemas allow for block content.
