### ISSUE TITLE
Docs: improve index.html

### ISSUE THREAD

**Issue by nokome** [stencila/schema#152]
We finally :blush: have an index page https://schema.stenci.la/. However, it could do with some improvements. I suggest that we keep the current page as `/alphabetic.html` with the following minor tweaks:

- give it a title
- make it an unordered list
- add tags for role, status, category

Then create a new page `/categories.html` that groups the schemas by the `category` property with tags for `role` and `status`

Then convert add links to those, and the files in `docs` into the  `README.md` and convert it to `index.html`.

**Comment by nokome** [comment]
In 0908532d93c71f1977fb6edaed758699190f9907 the `title` was added to the README metadata, unfortunately that doesn't look great here:

![image](https://user-images.githubusercontent.com/1152336/72688424-ece21380-3b6b-11ea-87af-02f1f05b8eb8.png)

Instead, we should add

**Comment by alex-ketch** [comment]
> Instead, here we should do something like:…

That was actually my first approach, however due to how Encoda converts it to HTML, we end up with two titles and thought that it looked a bit odd.
But since then I moved the list of schemas above the README content, and so it doesn't look as weird. Can make followup PR if you think that's ok
