### ISSUE TITLE
Schema v0.38.0+ are not supported in browser environments

### ISSUE THREAD

**Issue by alex-ketch** [stencila/schema#178]
As can be seen in [build log for v0.38.0](https://travis-ci.org/github/stencila/schema/jobs/653733345#L310), the changes in that version introduce dependency on `fs` and `path` Node modules.

> ```
> Creating a browser bundle that depends on Node.js built-in module ('path').
> You might need to include https://www.npmjs.com/package/rollup-plugin-node-builtins
> ```

There is a need to run several of the schema node factory functions (`codeChunk({…})`, etc.), on the front end. With the above changes it is not possible to build those packages without adding bloat with the polyfills, which I'm honestly not sure would function out of the box.

A relatively simple first step could be to omit `jsonld`, `jsonSchemas`, and `microdata` packages from browser builds. A bit more involved refactor could include removing the dynamic file reads, but not sure it'll be possible for all functions without trying (`microdata` file should be relative simple though) .

https://github.com/stencila/schema/blob/a7ae82a9fd6cd35c849ff6f8a2434487dba1bc77/ts/util/index.ts#L1-L6

**Comment by nokome** [comment]
Thanks for posting this, I came across a related issue a few days ago that I created a workaround for - https://github.com/stencila/schema/commit/7dd52a583300ab32db983f669ac637a1c979a7e5 - but thought at the time we needed a longer term solution. 

I agree with your suggestion of having a separate browser build as a first step. I id a little research at the time and it appears that microbundle supports that: https://github.com/developit/microbundle/issues/545#issuecomment-579869678
