### ISSUE TITLE
fix: Add issue type for schema CreativeWork

### ISSUE THREAD

**Issue by asisiuc** [stencila/schema#207]
The diagram lacks issue number when converting articles with the help of JATS codec (from stencila/encoda). In the repository [STENCILA ENCODA]( https://github.com/stencila/encoda/)  we opened the respective issue [ISSUE ENCODE 653](https://github.com/stencila/encoda/issues/653). Before doing that changes on encoda we need those type.

**Comment by nokome** [comment]
Please see https://github.com/stencila/encoda/pull/654#issuecomment-680708471 for why I don't think that an `issue` property is necessary. If you agree, could you please close this issue. But I'm also happy to discuss further if you disagree :slightly_smiling_face:
