### ISSUE TITLE
fix: Add subjects type for schema CreativeWork

### ISSUE THREAD

**Issue by asisiuc** [stencila/schema#209]
The diagram lacks subjects when converting articles with the help of JATS codec (from stencila/encoda). In the repository [STENCILA ENCODA]( https://github.com/stencila/encoda/) has already been opened the respective issue [ISSUE ENCODE 468](https://github.com/stencila/encoda/issues/468). Before doing that changes on encoda we need those type.

**Comment by nokome** [comment]
Closed by #210
