### ISSUE TITLE
Regression with TS type guards in v1.8

### ISSUE THREAD

**Issue by alex-ketch** [stencila/schema#271]
Some of the type guards in v1.8 return a `never` instead of the type refinement.
This causes build errors downstream when using these functions to narrow Node types,

E.g.

[**Before (v1.7.3)**](https://unpkg.com/browse/@stencila/schema@1.7.3/dist/ts/util/guards.d.ts):

```ts

/**
--
* Type guard to determine whether a node is a `Code`.
*
* @param {Node} node The node to get the type for
* @returns {(node is Code)}
*/
export declare const isCode: (node?: Node | undefined) => node is import("../types").CodeTypes;
```

[**After (^v1.8)**](https://unpkg.com/browse/@stencila/schema@1.8.0/dist/ts/util/guards.d.ts):

```ts
/**
 * Type guard to determine whether a node is a `Code`.
 *
 * @param {Node} node The node to get the type for
 * @returns {(node is Code)}
 */
export declare const isCode: (node?: Node | undefined) => node is never

```

**Comment by nokome** [comment]
Thanks for creating this, I noticed the bug myself last night. I suspect it is related to this change in the definition / construction of the `Node` union type: https://github.com/stencila/schema/commit/b658222f540ae107c458e9b5f9902140c3863941#diff-68fd41f8da64db8692a1a41ac84dc4cf4879fb428304972755442d5026ceaf55
