### ISSUE TITLE
Review SoftwareApplication and SoftwareSourceCode attributes

### ISSUE THREAD

**Issue by beneboy** [stencila/schema#4]
The implementation of SoftwareApplication has differed from schema.org definition by adding attributes that are defined on SoftwareSourceCode:

programmingLanguage, runtimePlatform and codeRepository 

This needs to be reviewed to see how to bring it more in line with the schema definition.

**Comment by nokome** [comment]
This is codemeta issue is very relevant to this issue: https://github.com/codemeta/codemeta/issues/198. I plan to follow up there soon.

**Comment by nokome** [comment]
We already had a custom `SoftwarePackage` class which extends `SoftwareSourceCode` and adds some properties from `SoftwareApplication`. So I've taken those extra from properties from SA and add other, different properties, to SP. This keeps SA inline with schema.org.
