### ISSUE TITLE
Generate documentation from JSON instead of YAML files

### ISSUE THREAD

**Issue by alex-ketch** [stencila/schema#43]
Currently documentation is generated using `.schema.yaml` files, we propose to use the newly compiled `.schema.json` files.
This will allow for documented schemas more accurately, reduce parsing complexity, and bring several other benefits to documentation generation.

**Comment by nokome** [comment]
Now possible with https://github.com/stencila/schema/pull/46

**Comment by nokome** [comment]
Just to note that we now have additional attributes that may be useful for docs:

- `parent` schema
- `children` schemas
- `source` e.g. `https://github.com/stencila/schema/blob/master/schema/CreativeWork.schema.yaml`
- `category` e.g. `data`
- `role` e.g. `primary`, `base`
- `status` e.g. `experimental`
- on each property, the ancestor the property was inherited `from`

See for example: https://stencila.github.io/schema/CreativeWork.schema.json
