### ISSUE TITLE
Render $refs in JSON schema as links to pages for the related schemas

### ISSUE THREAD

**Issue by alex-ketch** [stencila/schema#44]
Currently we do not parse `$ref` properties as references/links to other schemas. This makes understanding more difficult than it should be.
We should instead automatically detect `$ref` values as links to other schemas and render them as such.

**Comment by nokome** [comment]
This is no longer relevant because `$ref`s are now authored in YAML as just the type name e.g. `$ref: DatatableColumn`, rather than `$ref: DatatableColumn.schema.yaml`.
