### ISSUE TITLE
Develop mdx components necessary for creating narrative focused documentation pages

### ISSUE THREAD

**Issue by alex-ketch** [stencila/schema#45]
Reference for a narrative focused documentation page: https://developers.google.com/search/docs/data-types/occupation#example

- [ ] Allow for more informative and readable doc pages by using .mdx files
- [ ] Ensure `<PropertiesTable>` and other components are able to be used within `.mdx` documents
- [ ]  Create a default `.mdx` template if none available for the schema type
- [ ] Create component to show a concrete use case of a schema and its JSON component. A UI similar to [Google’s Testing Tool](https://search.google.com/structured-data/testing-tool) would be ideal

--- 

Pseudocode example usage of `PropertiesTable`

``` mdx
# Dataset

Some blurb on dataset type....

<PropertiesTable></PropertiesTable>

Here is an example of a Tabular Data Package converted to a `Dataset`:

<Example>
    <ExampleSource file="examples/datapackage.json">
    <ExampleResult file="examples/datapackage-generated.json">
</Example>

Here is an example of a Excel file converted to a `Collection` with several `Dataset`s:

<Example>
    <ExampleSource file="examples/collection.xlsx">
    <ExampleResult file="examples/collection-generated.json">
</Example>
```

**Comment by nokome** [comment]
Closing as we are now taking different approach to doc generation.
