### ISSUE TITLE
Review documentation & add examples for the following schemas

### ISSUE THREAD

**Issue by alex-ketch** [stencila/schema#58]
Continuation of #56 

- [x] CreativeWork
- [x] Article
- [x] Table
- [x] TableCell
- [x] TableRow
- [x] BlockContent
- [x] Blockquote
- [x] Code
- [x] CodeBlock
- [x] Expression
- [x] InlineContent
- [x] Link
- [x] List
- [x] Quote

**Comment by nokome** [comment]
Calling this closed (but not ruling out need for further refinements).
