### ISSUE TITLE
Add documentation for schema types

### ISSUE THREAD

**Issue by alex-ketch** [stencila/schema#82]
Below is a list of schemas missing documentation. Could also be that not all of them require full fledged documentation.

Please comment below when you start working on a schema, and check it off when it is completed and merged. Thanks!

---

- [ ] Include
- [ ] Node
- [ ] Thing
- [ ] Datatable (@nokome)
- [ ] DatatableColumn (@nokome)
- [ ] DatatableColumnSchema (@nokome)
- [ ] CodeChunk
- [ ] CodeExpr
- [ ] Environment
- [ ] Mount
- [ ] BlockContent
- [ ] Code 
- [ ] CodeBlock 
- [x] Delete
- [ ] Emphasis (@beneboy)
- [ ] Heading (@beneboy)
- [ ] InlineContent
- [x] Link (@alex-ketch)
- [x] Paragraph (@alex-ketch)
- [x] Quote (@alex-ketch)
- [x] QuoteBlock (@alex-ketch)
- [x] Strong (@alex-ketch)
- [x] ThematicBreak (@alex-ketch)

---

<details>
<summary>VSCode Snippet for document template</summary>

```json
{
  "Schema Example": {
    "prefix": "schemaDoc",
    "body": [
      "# $1",
      "",
      "The `$1` schema represents a $0",
      "",
      "## Examples",
      "",
      "### Simple",
      "",
      "```json validate",
      "{",
      "\"type\": \"$1\"",
      "}",
      "```",
      "",
      "## Related",
      "",
      "### HTML",
      "",
      "`$1` is analagous to the HTML [`<$1>`](https://developer.mozilla.org/en-US/docs/Web/HTML/Element) element.",
      "",
      "### JATS",
      "",
      "`$1` is analagous to the JATS [`<$1>`](https://jats.nlm.nih.gov/articleauthoring/tag-library/1.2/element/aut-elem-sec-intro.html) element.",
      "",
      "### mdast",
      "",
      "`$1` is analagous to the mdast [`$1`](https://github.com/syntax-tree/mdast#$1) node.",
      "",
      "### OpenDocument",
      "",
      "`$1` is analagous to the OpenDocument",
      "[`<$1>`](http://docs.oasis-open.org/office/v1.2/os/OpenDocument-v1.2-os-part1.html)",
      "element.",
      "",
      "### Pandoc",
      "",
      "`$1` is analagous to the Pandoc",
      "[`$1`](https://github.com/jgm/pandoc-types/blob/1.17.5.4/Text/Pandoc/Definition.hs#L217)",
      "type."
    ]
  }
}
```

</details>

**Comment by nokome** [comment]
Just to update this. I've put my name next to `Datatable` and related nodes and will tackle tomorrow.

@alex-ketch: When you have done #91, you may want to update `Table` and related nodes.
