### ISSUE TITLE
docs: add documentation for types and properties

### ISSUE THREAD

**Issue by nokome** [stencila/schema#9]
This is a proposal for how to write doc comments for classes and properties. 

Any documentation should come from the schema that the class/property implements. This is going to mean a lot of copy and pasting and potential for the doc comment to become out of sync with the source documentation. But having documentation in code is really useful for developers because, especially because many editors show this documentation in tool tips etc.

So, the proposal is to copy the documentation from the source schema and provide a link to that canonical documentation using the `@see` and `@link` tags. For example, for `Thing.name`:

```typescript
  /**
   * The name of the item.
   * 
   * @see {@link https://schema.org/name}
   */
  @property('schema:name')
  name: Text = ''
```

This then, get's usefully displayed in editors (e.g. VS Code):

![image](https://user-images.githubusercontent.com/1152336/48924469-7329a800-ef1d-11e8-9123-15842672a6d7.png)

And in our own generated documentation as:

![image](https://user-images.githubusercontent.com/1152336/48924444-16c68880-ef1d-11e8-805f-79b4b5d80fa3.png)

**Comment by apawlik** [comment]
This is a great idea (and I again learnt something). I am not sure what would be the potential shortcomings for this approach. Developers having to look up the details following the link from the source code?

**Comment by nokome** [comment]
Thanks for the feedback.

> Developers having to look up the details following the link from the source code?

Yeah, but the only other alternative is to put more of the details in the doc comments - which creates more risk of getting out of sync with the official docs. I think this approach strikes a balance between having something useful for developers and repeating everything that is in the offical docs. And regardless, there is often not that much extra detail (at least for schema.org).
