### ISSUE TITLE
Entity type

### ISSUE THREAD

**Issue by nokome** [stencila/schema#96]
Currently we mirror schema.org and have `Thing` as the base type. In addition to the schema.org `Thing` properties like `name` and `description`, we have added `type` and `id` to mimic JSON-LD's `@type` and `@id`. The `type` property is essential for doing runtime resolution of node types. We are not using the `id` property yet, but it will also be essential when we come to linking nodes within documents for reactivity.

The problem with this approach is that `Thing` comes with other properties like `name`, `alternateNames`  and `url`. Those are optional so you don't have to use them, but it:
  - makes the schema for derived nodes e.g. `Delete` look bloated (only `type` and `content` really matter)
  - is confusing because often the properties will be lost in conversion e.g. you _could_ add a `description` property to a `Delete` node in JSON, but it would be lost in conversion to Markdown, HTML, JATS, Word etc 

![image](https://user-images.githubusercontent.com/1152336/61563069-ea243a00-aac6-11e9-8ead-b7518b4d5991.png)

So, this issue proposes that:

- we create a new type called `Entity` which only has `type` and `id` properties
- `Entity` be the base type for `Thing`
- we use `Entity` as the base type for node types where using `Thing` adds properties that are not supported in the majority of formats which the node type will be used in.
- we document these schema design principles

@beneboy @alex-ketch Thoughts?

**Comment by beneboy** [comment]
Yes this makes sense. There might be some confusion when to inherit from Thing vs Entity but developers can hopefully follow along with existing schema and work it out.

**Comment by nokome** [comment]
Closed by #100.
